version: "3"

services:
  nginx:
    ports:
      - "3030:80"

  node-app :
    build : 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment :
      NODE_ENV: development
      PGUSER: root
      PGHOST: pg-db
      PGPASSWORD: 4321
      PGDATABASE: mydb
      PGPORT: 5432
      APIKey: c95696e3-8196-4e4c-8bc6-958a182725fc
      
    command: npm run dev

  pg-db :
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes: 
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql