version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3030:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app :
    build : .
    environment :
      PORT: 3030
      NODE_ENV: development
      PGUSER: root
      PGHOST: pg-db
      PGPASSWORD: 4321
      PGDATABASE: mydb
      PGPORT: 5432
    depends_on :
      - pg-db

  pg-db : 
    image : postgres
    restart : always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes: 
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-db:/var/lib/postgresql/data

volumes:
  pg-db: