name: deploy master branch
on:
  push:
    branches:
      - master

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v3   
      # - name: Use Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16.x

      # - name: Install Yarn
      #   run: npm install yarn@latest -g

      # - name: Install dependencies
      #   run: yarn

      # - name: Run build
      #   run: yarn build

      # - name: Run deploy
      #   uses: lowply/deploy-firebase@v0.0.5
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #     FIREBASE_PROJECT: test-cd-firebase

  update-version:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
        with:   
          branch: dev
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          version_format: "${major}.${minor}.${patch}"
      - 
        name: Update package.json
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.versioning.outputs.version }}   
      - 
        name: Commit & Push changes
        uses: actions-js/push@master
        id: updateversion
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          tags: true
          force: true
          message: 'Update package.json version to ${{ steps.versioning.outputs.version }}'
      -
        name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.versioning.outputs.version }}