name: deploy dev branch
on:
  push:
    branches:
      - dev

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
        with:   
          branch: dev
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          version_format: "${major}.${minor}.${patch}"
      - 
        name: Update package.json
        id: info
        uses: jaywcjlove/github-action-package@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.versioning.outputs.version }}   
      - 
        name: Commit & Push changes
        uses: actions-js/push@master
        id: updateversion
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          tags: true
          force: true
          message: 'Update package.json version to ${{ steps.versioning.outputs.version }}'
      -
        name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.versioning.outputs.version }}